#!/usr/bin/python

import serial
import time

arduino = serial.Serial('/dev/ttyACM0',baudrate=9600,timeout = 3.0)

while True:
	
	arduino.write("1")
	print("Encendido\n")
	time.sleep(1)
	
	
	arduino.write("0")
	print("Apagado\n")
	time.sleep(1)
	
arduino.close()
